app/models.py
from flask_sqlalchemy import SQLAlchemy

#instantiate an instnace of our ORM to handle database communication
db = SQLAlchemy()    # you can name this variable anything you want

# define a model - a model is  going to be an entity/a table in our database
# and we can define it with the SQL CREATE TABLE in mind(what do I want? what SQL database tyoes will those columns be? COnstraints?)

class Animation(db.Model):  # lets our project know that Animation is a table in our database
    id = db.Column(db.Integer, primary_key=True)  # primary_key makes it a SERIAL
    name_of_show = db.Column(db.String(200), nullable=False, unique =True)
    network = db.Column(db.String(100))
    birthday_party_fee = db.Column(db.String(100))
    main_characters = db.Column(db.String(200))

    def to_dict(self):    # method to convert into a dictionary
        return {
            'id': self.id,
            'name_of_show': self.name_of_show,
            'network': self.network,
            'birthday_party_fee': self.birthday_party_fee,
            'main_characters': self.main_characters
        }

app/forms.py
# imports that I'll need to work with WTForms: generic form template, whatever types of data fields you intned to use, and whatever validators you intend to use.
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, IntegerField, DecimalField, SubmitField
from wtforms.validators import DataRequired

# creating a new form - we're going to be making a class that inherits some behavior from FlaskForm

class newCartoonForm(FlaskForm):
    # what we have inside this class is whatever data fields we intend our form to have
    name_of_show = StringField('Name', validators=[DataRequired()])
    network = StringField('Network')
    birthday_party_fee = StringField('Birthday Party Fee')  # if using DecimalField it could throw error if DataRequired is not applied and left empty
    main_characters = StringField('Main Characters')        # empty field is actually an empty string ''. Could also use StringField instead
    submit_button = SubmitField()

app/__init__.py
# imports - the flask object which our app will be an instance of and the Config class we just made
from flask import Flask
from config import Config

# import our blueprints for registration
from .cartoon_characters.routes import character

# import our database stuff
from .models import db     # db is the instance created in models.py
from flask_migrate import Migrate

# instantiate the instance of our application
app = Flask(__name__)

# register our blueprints
app.register_blueprint(character)

# configure that app from our config file
app.config.from_object(Config)

# configure our database to work with our app
db.init_app(app)

migrate = Migrate(app, db)

# tell our newly instantiated app where it can find its traffic controller (aka routes)
from . import routes
from . import models
# from our app folder (.) import routes
# could also use 2 dots (..) to go further back in our project files/folders

app/cartoon_characters/routes.py
# within your blueprint's routes file - the first step is to instantaite 
# the blueprint and make sure that the blueprint is registered and can communicate with the larger app

from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.forms import newCartoonForm

# database imports
from app.models import db, Animation

# create the instance o four blueprint
character = Blueprint('cartoon_characters', __name__, template_folder='cartoon_characters_templates')

#when we're using blueprints - our routing decorator syntax is slightly changed
# @<blueprint_name>.route('/<url_endpoint>', [methods=<'GET','POST','PUT'>])
# def <routefuncname>():

# from here its like our other routes.py file - just creating routes for our movies blueprint
@character.route('/favoritecartoon')
def favoritecartoon():
    list_of_characters = "Bender from Futurama", "Arthur", "Bart Simpson", "Finn & Jake from Adventure Time" 
    return render_template('favoritecartoon.html', a_cartoon = list_of_characters)

@character.route('/addcartoon', methods=['GET', 'POST'])
def addcartoon():
    form = newCartoonForm()
    if request.method == 'POST':
        # do stuff with the form that the user submitted
        # first we need to check if the form validates
        if form.validate_on_submit():
            # create an instance of our Animation table
            # keywords should match what is in your models.py
            new_cartoon = Animation(name_of_show=form.name_of_show.data, network=form.network.data, birthday_party_fee=form.birthday_party_fee.data, main_characters=form.main_characters.data)
            
            # put that instance of Animation into our database
            db.session.add(new_cartoon)
            db.session.commit()
            
            # you can use the 'new_cartoon' instance and pass the .to_dict method to display what was added
            flash('New Cartoon Added!', category='alert-info')
            flash(f'{new_cartoon.to_dict()}', category='alert-info')
        else:
            flash('Nop, try again buddy', category='alert-danger')

        return redirect(url_for('cartoon_characters.addcartoon'))
        # implied else when request.method == 'GET'
        # We just render the html file like normal
    return render_template('addcartoon.html', form=form)

app/routes.py
from flask.templating import render_template
from app import app

@app.route('/')
def home():
    cartoon_of_the_day = 'Tom & Jerry'
    return render_template('index.html', cartoon = cartoon_of_the_day)

app/templates/components/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block title %} {% endblock title %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../../static/css/main.css">
</head>
  <body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Dre</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('cartoon_characters.favoritecartoon') }}">Favorite Cartoons</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('cartoon_characters.addcartoon') }}">Add A New Cartoon</a>
                </li>
              </ul>
            </div>
          </nav>      
    </div>
    <div class="container-fluid">
        {% block content %}
        {% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends 'components/layout.html' %}

{% block title %} Hello People {% endblock title %}
{% block content %}
<h1>The cartoon of the day is: {{ cartoon }}</h1>
<img class="img-fluid" src="../../static/images/jerry.jpg">
{% endblock content %}